{% set name = "pyroute2" %}
{% set version = "0.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyroute2-{{ version }}.tar.gz
  sha256: d0995c8aeb96c0e4eed4d62e97c9d795000a1a33b747d6dc54326665857cf11c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - win_inet_pton  # [win]

test:
  imports:
    - pyroute2
    - pyroute2.bsd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/svinota/pyroute2
  summary: Python Netlink library
  license: GPL-2.0-or-later
  license_file: LICENSE.GPL.v2

extra:
  recipe-maintainers:
    - nehaljwani
