{% set name = "pyroute2" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyroute2-{{ version }}.tar.gz
  sha256: 97253f8a192e92ac29db9c159a50a59195d72f2b8cdcf20c069d59187fa49ad1

build:
  noarch: python
  entry_points:
    - ss2 = pyroute2.netlink.diag.ss2:run
    - pyroute2-decoder = pyroute2.decoder.main:run
    - pyroute2-dhcp-client = pyroute2.dhcp.cli:run
    - pyroute2-test-platform = pyroute2.config.test_platform:run
    - dhcp-server-detector = pyroute2.dhcp.server_detector:run
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - psutil
    - {{ virtual_pkg|default("__unix") }}
  {% if virtual_pkg == "__win" %}
    - win_inet_pton
  {% endif %}

test:
  {% if virtual_pkg == "__unix" %}
  # On Windows: No module named 'fcntl'
  imports:
    - pyroute2
    - pyroute2.bsd
    - pyroute2.bsd.pf_route
    - pyroute2.bsd.rtmsocket
    - pyroute2.config
    - pyroute2.inotify
    - pyroute2.iproute
    - pyroute2.netlink
    - pyroute2.netlink.devlink
    - pyroute2.netlink.diag
    - pyroute2.netlink.event
    - pyroute2.netlink.generic
    - pyroute2.netlink.ipq
    - pyroute2.netlink.nfnetlink
    - pyroute2.netlink.nl80211
    - pyroute2.netlink.rtnl
    - pyroute2.netlink.rtnl.ifinfmsg
    - pyroute2.netlink.rtnl.ifinfmsg.plugins
    - pyroute2.netlink.rtnl.tcmsg
    - pyroute2.netlink.taskstats
    - pyroute2.netlink.uevent
    - pyroute2.netns
    - pyroute2.protocols
    - pyroute2.requests
  {% endif %}
  commands:
    - pip check
  {% if virtual_pkg == "__unix" %}
    - ss2 --help
    - pyroute2-decoder --help
    - pyroute2-dhcp-client --help
    - pyroute2-test-platform --help
    - dhcp-server-detector --help
  {% endif %}
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/svinota/pyroute2
  summary: Python Netlink library
  license: GPL-2.0-or-later OR Apache-2.0
  license_file:
    - LICENSE.GPL-2.0-or-later
    - LICENSE.Apache-2.0

extra:
  recipe-maintainers:
    - nehaljwani
