{% set name = "pyroute2" %}
{% set version = "0.7.12" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/p/pyroute2/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.core

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.ethtool

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.ipdb

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.ipset

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.ndb

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.nftables

  - url: https://files.pythonhosted.org/packages/39/16/323b947c34530436658331e2cf393b72ebcbd923a75154a7efb28feefd5d/pyroute2-{{ version }}.tar.gz
    sha256: 54d226fc3ff2732f49bac9b26853c50c9d05be05a4d9daf09c7cf6d77301eff3
    folder: pyroute2.nslink

  - url: https://pypi.io/packages/source/p/pyroute2.minimal/pyroute2.minimal-{{ version }}.tar.gz
    sha256: 64e6c923e45e4b1783f019497468ff4e77abbd8bb88a7f21288cb7dd37399276
    folder: pyroute2.minimal

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: pyroute2.core
    build:
      noarch: python
      script:
        - cd pyroute2.core
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - psutil >=5.0
    test:
      imports:
        - pr2modules
        - pr2modules.bsd
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: the core'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ethtool
    build:
      noarch: python
      script:
        - cd pyroute2.ethtool
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        # Import fails on Windows due to lack of fcntl
        # - pr2modules.ethtool
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ethtool'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipdb
    build:
      noarch: python
      script:
        - cd pyroute2.ipdb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.ipdb
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: IPDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ipset
    build:
      noarch: python
      script:
        - cd pyroute2.ipset
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: ipset'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.ndb
    build:
      noarch: python
      entry_points:
        - pyroute2-cli = pr2modules.ndb.cli:run
      script:
        - cd pyroute2.ndb
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
        - pyroute2.nslink
    test:
      imports:
        - pr2modules
        - pr2modules.cli
      commands:
        - pip check
        - pyroute2-cli --help
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NDB module'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nftables
    build:
      noarch: python
      script:
        - cd pyroute2.nftables
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nftables
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: nftables'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.nslink
    build:
      noarch: python
      script:
        - cd pyroute2.nslink
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core
    test:
      imports:
        - pr2modules
        - pr2modules.nslink
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: NetNS, NSPopen and remote modules'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2.minimal
    build:
      noarch: python
      script:
        - cd pyroute2.minimal
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: 'Python Netlink library: minimal installation'
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

  - name: pyroute2
    build:
      noarch: python
      script:
        - cd pyroute2
        - {{ PYTHON }} -m pip install --no-deps . -vv
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools
      run:
        - python >=3.6
        - pyroute2.core =={{ version }}
        - pyroute2.ethtool =={{ version }}
        - pyroute2.ipdb =={{ version }}
        - pyroute2.ipset =={{ version }}
        - pyroute2.ndb =={{ version }}
        - pyroute2.nftables =={{ version }}
        - pyroute2.nslink =={{ version }}
        - importlib-metadata
    test:
      imports:
        - pyroute2
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://github.com/svinota/pyroute2
      summary: Python Netlink library
      license: GPL-2.0-or-later OR Apache-2.0
      license_file:
        - LICENSE.GPL.v2
        - LICENSE.Apache.v2

about:
  home: https://github.com/svinota/pyroute2
  summary: Python Netlink library
  license: GPL-2.0-or-later OR Apache-2.0
  license_file:
    - LICENSE.GPL.v2
    - LICENSE.Apache.v2

extra:
  feedstock-name: pyroute2
  recipe-maintainers:
    - nehaljwani
